### ISSUE TITLE
Doesn't seem to work with reCAPTCHA v3

### ISSUE THREAD

**Issue by samkent** [impress-org/give-snippet-library#105]
I've used this snippet with reCAPTCHA V3, but I get the following error:

ERROR for site owner: Invalid key type. 

I assume this is because the plugin is only compatible with V2?

**Comment by mathetos** [comment]
Yes, this snippet is intended for use with reCAPTCHA v2 only currently.

**Comment by samkent** [comment]
Cool, thanks @mathetos :)
