### ISSUE TITLE
ADD: New snippet that allows custom data to be sent to PayPal's "Notes"

### ISSUE THREAD

**Issue by mathetos** [impress-org/give-snippet-library#38]
We need a snippet that allows admins to send custom data to PayPal similarly to our existing Stripe snippet:

https://github.com/WordImpress/Give-Snippet-Library/blob/master/gateway-customizations/stripe-pass-custom-meta-for-customers.php

**Comment by DevinWalker** [comment]
Issue moved to [WordImpress/Give-PayPal-Pro #48](https://github.com/WordImpress/Give-PayPal-Pro/issues/48) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Benunc** [comment]
I still think this is a needed snippet for PayPal standard.

**Comment by mathetos** [comment]
@DevinWalker I know you created a filter for this. Can you provide a snippet as an example for how to customize the NOTES that get sent now?

**Comment by Benunc** [comment]
User asking about this @DevinWalker https://secure.helpscout.net/conversation/428559403/10205/

**Comment by Benunc** [comment]
This is an OLD issue, but we get a not-insignificant amount of requests to send additional data to PayPal Standard. This issue added a filter for PayPal Pro, but `give_paypal_redirect_args` already exists for PayPal standard. I would just love a working snippet that sends data to standard, using that filter.

Most recently, the customer is looking to send tribute data, so something similar to this, but for PayPal: 

https://github.com/impress-org/give-snippet-library/blob/master/add-on-snippets/stripe/add-tributes-meta.php

**Comment by DevinWalker** [comment]
We've discussed this a number of times and there isn't a good solution for sending custom data to PayPal via Standard.
