### ISSUE TITLE
Showing the Donation List in Place of Donor List

### ISSUE THREAD

**Issue by raftaar1191** [impress-org/give-snippet-library#60]
Here from the filename and from the shortcode description user think that it's is going to display the Donor details with the total Amount that they have donated but it showing the Donation details in ASC order and the amount is the Donation amount that is being given by Donor.

##Related issues
https://github.com/WordImpress/Give-Snippet-Library/issues/51

Video Link: https://screencast-o-matic.com/watch/cFn1XFogNy

File Link: https://github.com/WordImpress/Give-Snippet-Library/blob/master/useful-queries/better-donor-list-shortcode.php

![image](https://user-images.githubusercontent.com/22215595/35856810-215cabc0-0b5d-11e8-8be5-42e7b8417fb5.png)

![image](https://user-images.githubusercontent.com/22215595/35856816-28c2536a-0b5d-11e8-9daf-276c85e37c83.png)

![image](https://user-images.githubusercontent.com/22215595/35856831-30b69c98-0b5d-11e8-938f-2eade6cd9d15.png)

**Comment by kevinwhoffman** [comment]
Closing as this snippet is no longer necessary since we have an official donor wall shortcode.
