### ISSUE TITLE
Authorize phone snippet not working with webhooks

### ISSUE THREAD

**Issue by plethoradesign** [impress-org/give-snippet-library#69]
I created the authorizenet-phonenumber-from-custom-field.php snippet for sending phone numbers to Authorize.net, but this does not work with the 1.3.3 version of Give, due to the change to webhooks.

I had a look at 
[https://developer.authorize.net/api/reference/features/webhooks.html] but am none the wiser. I'd like to make a version of the snippet that works with 1.3.3  - maybe someone can give some ideas on how I would start on that?

**Comment by DevinWalker** [comment]
Please log support questions here: https://wordpress.org/support/plugin/give
