### ISSUE TITLE
fix(give-snippet-library): better-donor-list-shortcode.php passing in two $ to the total amount

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give-snippet-library#71]
## User Story
As a site admin, I want to be able to implement the code snippet without seeing two $ appear before the total

## Current Behavior
I currently see two $ before the amount total.

## Expected Behavior
I expect to see just one $

## Steps to Reproduce
1. Upload and install snippet plugin
2. Place the shortcode into a page 
3. See that is displays $$ before the total.

## Visuals
<img width="476" alt="screen shot 2018-04-12 at 7 18 24 pm" src="https://user-images.githubusercontent.com/20672471/38708910-6800d694-3e86-11e8-8d86-3fb38ac5bfad.png">

## Related
https://secure.helpscout.net/conversation/559228262/16813?folderId=1823994

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://give.local
Site URL: http://give.local
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.local
TLS Connection: Connection uses The website calling howsmyssl.com's API has been making many calls and does not have a subscription. See https://subscriptions.howsmyssl.com/signup for how to get one.
TLS Connection: ( ! ) Notice: Undefined property: stdClass::$rating in /app/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php on line 199
Call Stack
#TimeMemoryFunctionLocation
10.0000367272{main}(  ).../edit.php:0
20.0003367944require_once( '/app/public/wp-admin/admin.php' ).../edit.php:10
30.29347395296do_action(  ).../admin.php:224
40.29347395672WP_Hook->do_action(  ).../plugin.php:453
50.29347395672WP_Hook->apply_filters(  ).../class-wp-hook.php:310
60.29347396800Give_Admin_Settings->output(  ).../class-wp-hook.php:286
70.29737445504include( '/app/public/wp-content/plugins/give/includes/admin/views/html-admin-settings.php' ).../class-admin-settings.php:263
80.29797448024do_action(  ).../html-admin-settings.php:109
90.29797448400WP_Hook->do_action(  ).../plugin.php:453
100.29797448400WP_Hook->apply_filters(  ).../class-wp-hook.php:310
110.29797449528Give_Settings_System_Info->output(  ).../class-wp-hook.php:286
120.29897455768include_once( '/app/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php' ).../class-settings-system-info.php:56
: 
: 
: 
1: 367272
2: 367944
3: 7395296
4: 7395672
5: 7395672
6: 7396800
7: 7445504
8: 7448024
9: 7448400
10: 7448400
11: 7449528
12: 7455768
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
: 
: 
: 
1: 367272
2: 367944
3: 7395296
4: 7395672
5: 7395672
6: 7396800
7: 7445504
8: 7448024
9: 7448400
10: 7448400
11: 7449528
12: 7455768

### Give Configuration ###

Give Version: 2.0.6
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access❌Renewal Receipt Email❌Subscription Cancelled Email
Upgraded From: 2.0.7
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give.local/donation-confirmation/
Failure Page: http://give.local/donation-failed/
Donation History Page: http://give.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Authorize.net Gateway: ❌ Unlicensed – by WordImpress – 1.3.3
Give - Braintree Gateway: ❌ Unlicensed – by WordImpress – 1.2
Give - CSV Toolbox: ❌ Unlicensed – by WordImpress – 1.0
Give - Currency Switcher: ❌ Unlicensed – by WordImpress – 1.0.3
Give - Fee Recovery: ❌ Unlicensed – by WordImpress – 1.5
Give - Form Field Manager: ❌ Unlicensed – by WordImpress – 1.2.8
Give - Manual Donations: ❌ Unlicensed – by WordImpress – 1.3.2
Give - PayPal Pro Gateway: ❌ Unlicensed – by WordImpress – 1.1.4
Give - PDF Receipts: ❌ Unlicensed – by WordImpress – 2.2.5
Give - Per Form Gateways: ❌ Unlicensed – by WordImpress – 1.0.1
Give - Recurring Donations: ❌ Unlicensed – by WordImpress – 1.5.7
Give - Sofort Payment Gateway: ❌ Unlicensed – by WordImpress, CoachBirgit – 1.0
Give - Stripe Gateway: ❌ Unlicensed – by WordImpress – 1.5.2
Give - Tributes: ❌ Unlicensed – by WordImpress – 1.4.1

### Other Active Plugins ###

Email Cop: by Ashfame – 0.1.1
Give - Hook Helper: by Ravinder Kumar – 1.0
Sam's Helper Function: by WordImpress – 1.0
Transients Manager: by Pippin Williamson – 1.7.4
WP Auto Login: by Ren Ventura – 1.0.1

### Inactive Plugins ###

Duplicate Post: by Enrico Battocchi – 3.2.1
Give - Custom Field Integration: by WordImpress – 1.0
Give - MailChimp: by WordImpress – 1.4
My Custom Functions: by Arthur Gareginyan – 4.13

### Theme ###

Name: Twenty Seventeen
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome </li>
    </ul>
</details>

**Comment by DevinWalker** [comment]
Hey @samsmith89 I'm unable to reproduce this:

![2018-04-12_17-10-13](https://user-images.githubusercontent.com/1571635/38710282-67b879e2-3e74-11e8-91d8-40eaba749dc7.png)

But we'll have the donor wall functionality coming out in 2.1 soon so the customer should be good to go. After that we'll deprecate this snippet.

**Comment by mikejhale** [comment]
Per note in HelpScout "no longer relevant". Can use Donor Wall instead.
