### ISSUE TITLE
fix: update the PDF custom tag snippet

### ISSUE THREAD

**Issue by Benunc** [impress-org/give-snippet-library#81]
The Current snippet is here: https://github.com/WordImpress/Give-Snippet-Library/blob/master/add-on-snippets/pdf-receipts/add-custom-tags.php

Problems with it:

1. It says it's for adding in custom tags, but it really is only for adding in amount.
2. When users ask for custom tags there, they are looking for the equivalent of our meta email tags, but for PDFs.

I'd like a better resource to send to them, specifically for Form Field Manager data. 

Related: 
https://github.com/WordImpress/Give-PDF-Receipts/issues/149

**Comment by kevinwhoffman** [comment]
@raftaar1191 Please add a new snippet showing how to add a custom tag for displaying data from Form Field Manager.

The snippet Ben provided should get you started. Remove the logic related to the amount and replace with logic to retrieve FFM data. https://github.com/WordImpress/Give-Snippet-Library/blob/master/add-on-snippets/pdf-receipts/add-custom-tags.php

**Comment by raftaar1191** [comment]
@Benunc @kevinwhoffman I have created a snipped for https://github.com/WordImpress/Give-Snippet-Library/issues/81#issuecomment-422092882 comment but that require the https://github.com/WordImpress/Give-PDF-Receipts/tree/release/2.3.1 Version to be released first


So we first need to release Give-PDF-Receipts Version 2.3.1 then only we can use the filter to add FFM custom tag support 

PR link: https://github.com/WordImpress/Give-Snippet-Library/pull/83

**Comment by raftaar1191** [comment]
@Benunc @kevinwhoffman 

I have also added this snipped in the PDF-receipt [version 2.3.1](https://github.com/WordImpress/Give-PDF-Receipts/tree/release/2.3.1) So once we release the PDF-receipt 2.3.1 this feature will be available to all the user.

**Comment by mehul0810** [comment]
## Slack Call Summary
Participants: @mehul0810 @ravinderk 
Topic: Discussion about existing PR and code improvement
Result: I'll create a new branch and merge existing PR into it and then improve code as required so that all the meta email tags work with PDF receipts. Also, will introduce a new filter to support Table Layout template which is a default for new users.

**Comment by mehul0810** [comment]
Closing this issue and related PR as we'll be implementing the feature within PDF receipts https://github.com/impress-org/give-pdf-receipts/issues/175.
