### ISSUE TITLE
feat: make incrementer plugin work when multiple forms are on a page

### ISSUE THREAD

**Issue by Benunc** [impress-org/give-snippet-library#85]
Currently, this snippet only works when a form is on a page by itself:

https://github.com/impress-org/give-snippet-library/blob/master/form-customizations/give-simple-ticket-incrementer.php

Customer request to make it work on pages with multiple forms.

**Comment by kevinwhoffman** [comment]
Discussed @mehul0810, we are going to move forward without support for currency switcher to simplify the issue.
