### ISSUE TITLE
show payment option to administrator only

### ISSUE THREAD

**Issue by amjad** [impress-org/give-snippet-library#96]
Is there a snippet to show Offline Donation option to logged in users that are administrator only? 
Thanks.

**Comment by kevinwhoffman** [comment]
Sorry we do not have a snippet for this right now and it would require custom development.

**Comment by amjad** [comment]
Maybe this could be a feature request? Because how else would an admin put in a manual donation say which is given by Cash. Unless adding a manual donation can be done from the backend.

**Comment by Benunc** [comment]
Hi @amjad 
Check out our manual donations add-on. That will do what you are looking for: 

https://givewp.com/addons/manual-donations/

Thanks!
