### ISSUE TITLE
feat: ensure multiple accounts for PayPal snippet also works for recurring donations 

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give-snippet-library#97]
# Feature Request

## User Story

As a site admin, I want the snippet that allows for multiple PayPal Standard accounts on a per-form basis to also work for Recurring Donations. This way my donors can give one-time and recurring donations to different PayPal accounts on my site based on the form they donate to.

## Possible Solution

Possibly find, or add a filter that supports this functionality and update the code snippet to conditionally change the PayPal URL if it's one-time or recurring.

Here's the link to the snippet:
https://github.com/impress-org/give-snippet-library/blob/62b821170e30a4aaf229b18faf4fbee7f84c95e6/gateway-customizations/paypal/paypal-standard-mutliple-accounts.php

## Related

https://secure.helpscout.net/conversation/793228811/35422

## Acceptance Criteria

- [ ] When I implement the snippet on my site it functions whether the donor selects one-time or recurring.

**Comment by ravinderk** [comment]
Note: Latest snippet is working fine for us. We are waiting for plugin user response about update snippet.

**Comment by samsmith89** [comment]
Confirmed this works. Closing
